export default {
  LIKE_SUCCESS: 'LIKE_SUCCESS',
  RECEIVE_LIKE: 'RECEIVE_LIKE',
  EDIT_POST: 'EDIT_POST',
  RECEIVE_EDIT_POST: 'RECEIVE_EDIT_POST',
  
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  RECEIVE_POST: 'RECEIVE_POST',
  
  RECEIVE_BOARD: 'RECEIVE_BOARD',
  
  DELETE_POST: 'DELETE_POST',
  RECEIVE_DELETE_POST: 'RECEIVE_DELETE_POST',
  
  LEAVE_SESSION: 'LEAVE_SESSION',
  JOIN_SESSION: 'JOIN_SESSION',
  CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS'
}