export default {
  JOIN_SESSION: 'JOIN_SESSION',
  CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
  RECEIVE_CLIENT_LIST: 'RECEIVE_CLIENT_LIST',
  LEAVE_SESSION: 'LEAVE_SESSION',
  RENAME_SESSION: 'RENAME_SESSION',
  RECEIVE_SESSION_NAME: 'RECEIVE_SESSION_NAME',
  LOAD_PREVIOUS_SESSIONS: 'LOAD_PREVIOUS_SESSIONS'
}